name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - main

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "main"
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml # located in .github/ in default branch
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.FRANKIE_PAT }}
